# Generated by Django 5.2.1 on 2025-05-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_university_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="University",
        ),
    ]
